# ML-Agents Training Configuration for Interceptor Drone
# This file should replace your current interceptor_pro.yaml

behaviors:
  "My Behavior":  # This matches the behavior name from Unity: "My Behavior?team=0"
    trainer_type: ppo
    
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        
    behavioral_cloning:
      demo_path: null
      strength: 0.0
      steps: 0
      
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000

# Environment settings
env_settings:
  env_path: null  # Will be set by command line argument
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  
# Checkpoint settings  
checkpoint_settings:
  run_id: "InterceptorTraining"
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: true
  inference: false
  
# Engine settings
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
