behaviors:
  DroneInterceptor:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 65536
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 4.0e6
    time_horizon: 128
    summary_freq: 5000
    checkpoint_interval: 500000
engine_settings:
  num_envs: 8
  no_graphics: true
  capture_frame_rate: 0
environment_parameters:
  difficulty:
    curriculum:
      - name: easy
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: DroneInterceptor
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.4
      - name: med
        value: 0.5
        completion_criteria:
          measure: reward
          behavior: DroneInterceptor
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
      - name: hard
        value: 1.0
